/*
 * InstitucionForm.java
 *
 * Created on 8 de agosto de 2008, 18:32
 */

package com.tdk.client.personas.institucion;

/**
 *
 * @author  fernando
 */
public class InstitucionForm extends javax.swing.JPanel {

    /** Creates new form InstitucionForm */
    public InstitucionForm() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlinstitucion = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        tbpnlDatos = new javax.swing.JTabbedPane();
        pnlContactos = new javax.swing.JPanel();
        pnlProfesores = new javax.swing.JPanel();
        pnlAlumnos = new javax.swing.JPanel();
        btnCancelar = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();
        lblMessage = new javax.swing.JLabel();

        pnlinstitucion.setBorder(javax.swing.BorderFactory.createTitledBorder(null, org.openide.util.NbBundle.getMessage(InstitucionForm.class, "InstitucionForm.pnlinstitucion.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("DejaVu Sans", 1, 13), java.awt.SystemColor.activeCaption)); // NOI18N

        jLabel1.setText(org.openide.util.NbBundle.getMessage(InstitucionForm.class, "InstitucionForm.jLabel1.text")); // NOI18N

        txtNombre.setText(org.openide.util.NbBundle.getMessage(InstitucionForm.class, "InstitucionForm.txtNombre.text")); // NOI18N

        javax.swing.GroupLayout pnlinstitucionLayout = new javax.swing.GroupLayout(pnlinstitucion);
        pnlinstitucion.setLayout(pnlinstitucionLayout);
        pnlinstitucionLayout.setHorizontalGroup(
            pnlinstitucionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlinstitucionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlinstitucionLayout.setVerticalGroup(
            pnlinstitucionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlinstitucionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlinstitucionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlContactos.setLayout(new java.awt.BorderLayout());
        tbpnlDatos.addTab(org.openide.util.NbBundle.getMessage(InstitucionForm.class, "InstitucionForm.pnlContactos.TabConstraints.tabTitle"), pnlContactos); // NOI18N

        pnlProfesores.setLayout(new java.awt.BorderLayout());
        tbpnlDatos.addTab(org.openide.util.NbBundle.getMessage(InstitucionForm.class, "InstitucionForm.pnlProfesores.TabConstraints.tabTitle"), pnlProfesores); // NOI18N

        pnlAlumnos.setLayout(new java.awt.BorderLayout());
        tbpnlDatos.addTab(org.openide.util.NbBundle.getMessage(InstitucionForm.class, "InstitucionForm.pnlAlumnos.TabConstraints.tabTitle"), pnlAlumnos); // NOI18N

        btnCancelar.setText(org.openide.util.NbBundle.getMessage(InstitucionForm.class, "InstitucionForm.btnCancelar.text")); // NOI18N

        btnAceptar.setText(org.openide.util.NbBundle.getMessage(InstitucionForm.class, "InstitucionForm.btnAceptar.text")); // NOI18N

        lblMessage.setText(org.openide.util.NbBundle.getMessage(InstitucionForm.class, "InstitucionForm.lblMessage.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tbpnlDatos, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE)
                    .addComponent(pnlinstitucion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblMessage, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAceptar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlinstitucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tbpnlDatos, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnAceptar)
                    .addComponent(lblMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAceptar;
    public javax.swing.JButton btnCancelar;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel lblMessage;
    public javax.swing.JPanel pnlAlumnos;
    public javax.swing.JPanel pnlContactos;
    public javax.swing.JPanel pnlProfesores;
    public javax.swing.JPanel pnlinstitucion;
    public javax.swing.JTabbedPane tbpnlDatos;
    public javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables

}
