/*
 * VigenciaForm.java
 *
 * Created on 12 de agosto de 2008, 17:41
 */

package com.tdk.client.utils.internal;

/**
 *
 * @author  fernando
 */
public class VigenciaForm extends javax.swing.JPanel {

    /** Creates new form VigenciaForm */
    public VigenciaForm() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chkFechaHasta = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        xdtpFechaDesde = new org.jdesktop.swingx.JXDatePicker();
        xdtpFechaHasta = new org.jdesktop.swingx.JXDatePicker();

        chkFechaHasta.setText(org.openide.util.NbBundle.getMessage(VigenciaForm.class, "VigenciaForm.chkFechaHasta.text")); // NOI18N

        jLabel1.setText(org.openide.util.NbBundle.getMessage(VigenciaForm.class, "VigenciaForm.jLabel1.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(xdtpFechaDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkFechaHasta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(xdtpFechaHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {xdtpFechaDesde, xdtpFechaHasta});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(xdtpFechaDesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkFechaHasta)
                    .addComponent(xdtpFechaHasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JCheckBox chkFechaHasta;
    public javax.swing.JLabel jLabel1;
    public org.jdesktop.swingx.JXDatePicker xdtpFechaDesde;
    public org.jdesktop.swingx.JXDatePicker xdtpFechaHasta;
    // End of variables declaration//GEN-END:variables

}
