/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tdk.client.torneos;

import com.thorplatform.swing.SwingControllerFactory;
import com.thorplatform.swing.actions.NotifierSwingActionListener;
import java.awt.BorderLayout;
import java.io.Serializable;
import java.util.logging.Logger;
import org.openide.util.Lookup;
import org.openide.util.NbBundle;
import org.openide.windows.TopComponent;
import org.openide.windows.WindowManager;
import org.openide.util.Utilities;

/**
 * Top component which displays something.
 */
final class ParametrizacionTopComponent extends TopComponent {

    private static ParametrizacionTopComponent instance;
    /** path to the icon used by the component and its open action */
    static final String ICON_PATH = "com/tdk/client/torneos/package_settings.png";
    private static final String PREFERRED_ID = "ParametrizacionTopComponent";
    private ParametrizacionController parametrizacionController;

    private ParametrizacionTopComponent() {
        initComponents();
        afeterInitComponents();
        setName(NbBundle.getMessage(ParametrizacionTopComponent.class, "CTL_ParametrizacionTopComponent"));
        setToolTipText(NbBundle.getMessage(ParametrizacionTopComponent.class, "HINT_ParametrizacionTopComponent"));
        setIcon(Utilities.loadImage(ICON_PATH, true));
    }

    private void afeterInitComponents() {
        SwingControllerFactory scf = Lookup.getDefault().lookup(SwingControllerFactory.class);
        parametrizacionController = scf.createController(ParametrizacionController.class);
        add(parametrizacionController.getForm(), BorderLayout.CENTER);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    /**
     * Gets default instance. Do not use directly: reserved for *.settings files only,
     * i.e. deserialization routines; otherwise you could get a non-deserialized instance.
     * To obtain the singleton instance, use {@link findInstance}.
     */
    public static synchronized ParametrizacionTopComponent getDefault() {
        if (instance == null) {
            instance = new ParametrizacionTopComponent();
        }
        return instance;
    }

    /**
     * Obtain the ParametrizacionTopComponent instance. Never call {@link #getDefault} directly!
     */
    public static synchronized ParametrizacionTopComponent findInstance() {
        TopComponent win = WindowManager.getDefault().findTopComponent(PREFERRED_ID);
        if (win == null) {
            Logger.getLogger(ParametrizacionTopComponent.class.getName()).warning(
                    "Cannot find " + PREFERRED_ID + " component. It will not be located properly in the window system.");
            return getDefault();
        }
        if (win instanceof ParametrizacionTopComponent) {
            return (ParametrizacionTopComponent) win;
        }
        Logger.getLogger(ParametrizacionTopComponent.class.getName()).warning(
                "There seem to be multiple components with the '" + PREFERRED_ID +
                "' ID. That is a potential source of errors and unexpected behavior.");
        return getDefault();
    }

    @Override
    public int getPersistenceType() {
        return TopComponent.PERSISTENCE_NEVER;
    }

    @Override
    public void componentOpened() {
        if (Lookup.getDefault().lookup(NotifierSwingActionListener.class).isIsLogin()) {
            parametrizacionController.initialice();
        }
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    /** replaces this in object stream */
    @Override
    public Object writeReplace() {
        return new ResolvableHelper();
    }

    @Override
    protected String preferredID() {
        return PREFERRED_ID;
    }

    final static class ResolvableHelper implements Serializable {

        private static final long serialVersionUID = 1L;

        public Object readResolve() {
            return ParametrizacionTopComponent.getDefault();
        }
    }
}
