/*
 * RegistrarCompetidorTorneoForm.java
 *
 * Created on 27 de agosto de 2008, 17:20
 */

package com.tdk.client.torneos;

/**
 *
 * @author  fernando
 */
public class RegistrarCompetidorTorneoForm extends javax.swing.JPanel {

    /** Creates new form RegistrarCompetidorTorneoForm */
    public RegistrarCompetidorTorneoForm() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCompetidores = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        xtreetblCompetidores = new org.jdesktop.swingx.JXTreeTable();
        btnQuitar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        tbarExpandAndCollapse = new javax.swing.JToolBar();
        btnExpand = new javax.swing.JButton();
        btnCollapse = new javax.swing.JButton();
        xtskpnlContainer = new org.jdesktop.swingx.JXTaskPaneContainer();
        tskpnlTorneo = new org.jdesktop.swingx.JXTaskPane();
        jLabel1 = new javax.swing.JLabel();
        cboTorneo = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnLimpiar = new javax.swing.JButton();

        pnlCompetidores.setBorder(javax.swing.BorderFactory.createTitledBorder(null, org.openide.util.NbBundle.getMessage(RegistrarCompetidorTorneoForm.class, "RegistrarCompetidorTorneoForm.pnlCompetidores.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("DejaVu Sans", 1, 13), java.awt.SystemColor.activeCaption)); // NOI18N

        jScrollPane1.setViewportView(xtreetblCompetidores);

        btnQuitar.setText(org.openide.util.NbBundle.getMessage(RegistrarCompetidorTorneoForm.class, "RegistrarCompetidorTorneoForm.btnQuitar.text")); // NOI18N
        btnQuitar.setEnabled(false);

        btnEditar.setText(org.openide.util.NbBundle.getMessage(RegistrarCompetidorTorneoForm.class, "RegistrarCompetidorTorneoForm.btnEditar.text")); // NOI18N
        btnEditar.setEnabled(false);

        btnAgregar.setText(org.openide.util.NbBundle.getMessage(RegistrarCompetidorTorneoForm.class, "RegistrarCompetidorTorneoForm.btnAgregar.text")); // NOI18N

        tbarExpandAndCollapse.setFloatable(false);

        btnExpand.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tdk/client/torneos/mas.png"))); // NOI18N
        btnExpand.setText(org.openide.util.NbBundle.getMessage(RegistrarCompetidorTorneoForm.class, "RegistrarCompetidorTorneoForm.btnExpand.text")); // NOI18N
        tbarExpandAndCollapse.add(btnExpand);

        btnCollapse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tdk/client/torneos/menos.png"))); // NOI18N
        btnCollapse.setText(org.openide.util.NbBundle.getMessage(RegistrarCompetidorTorneoForm.class, "RegistrarCompetidorTorneoForm.btnCollapse.text")); // NOI18N
        tbarExpandAndCollapse.add(btnCollapse);

        javax.swing.GroupLayout pnlCompetidoresLayout = new javax.swing.GroupLayout(pnlCompetidores);
        pnlCompetidores.setLayout(pnlCompetidoresLayout);
        pnlCompetidoresLayout.setHorizontalGroup(
            pnlCompetidoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCompetidoresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCompetidoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 866, Short.MAX_VALUE)
                    .addGroup(pnlCompetidoresLayout.createSequentialGroup()
                        .addComponent(tbarExpandAndCollapse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 545, Short.MAX_VALUE)
                        .addComponent(btnAgregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnQuitar)))
                .addContainerGap())
        );

        pnlCompetidoresLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAgregar, btnEditar, btnQuitar});

        pnlCompetidoresLayout.setVerticalGroup(
            pnlCompetidoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCompetidoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCompetidoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlCompetidoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnQuitar)
                        .addComponent(btnEditar)
                        .addComponent(btnAgregar))
                    .addComponent(tbarExpandAndCollapse, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        xtskpnlContainer.setBackground(new java.awt.Color(238, 238, 238));

        tskpnlTorneo.setBackground(new java.awt.Color(238, 238, 238));
        tskpnlTorneo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tdk/client/torneos/torneo-14x16.png"))); // NOI18N
        tskpnlTorneo.setTitle(org.openide.util.NbBundle.getMessage(RegistrarCompetidorTorneoForm.class, "RegistrarCompetidorTorneoForm.tskpnlTorneo.title")); // NOI18N
        tskpnlTorneo.setToolTipText(org.openide.util.NbBundle.getMessage(RegistrarCompetidorTorneoForm.class, "RegistrarCompetidorTorneoForm.tskpnlTorneo.toolTipText")); // NOI18N

        jLabel1.setText(org.openide.util.NbBundle.getMessage(RegistrarCompetidorTorneoForm.class, "RegistrarCompetidorTorneoForm.jLabel1.text")); // NOI18N

        cboTorneo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText(org.openide.util.NbBundle.getMessage(RegistrarCompetidorTorneoForm.class, "RegistrarCompetidorTorneoForm.jLabel2.text")); // NOI18N

        txtBuscar.setText(org.openide.util.NbBundle.getMessage(RegistrarCompetidorTorneoForm.class, "RegistrarCompetidorTorneoForm.txtBuscar.text")); // NOI18N

        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tdk/client/torneos/trash-16x16.png"))); // NOI18N
        btnLimpiar.setText(org.openide.util.NbBundle.getMessage(RegistrarCompetidorTorneoForm.class, "RegistrarCompetidorTorneoForm.btnLimpiar.text")); // NOI18N

        javax.swing.GroupLayout tskpnlTorneoLayout = new javax.swing.GroupLayout(tskpnlTorneo.getContentPane());
        tskpnlTorneo.getContentPane().setLayout(tskpnlTorneoLayout);
        tskpnlTorneoLayout.setHorizontalGroup(
            tskpnlTorneoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tskpnlTorneoLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboTorneo, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        tskpnlTorneoLayout.setVerticalGroup(
            tskpnlTorneoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tskpnlTorneoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(tskpnlTorneoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cboTorneo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpiar)))
        );

        xtskpnlContainer.add(tskpnlTorneo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(xtskpnlContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 912, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(pnlCompetidores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(xtskpnlContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlCompetidores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAgregar;
    public javax.swing.JButton btnCollapse;
    public javax.swing.JButton btnEditar;
    public javax.swing.JButton btnExpand;
    public javax.swing.JButton btnLimpiar;
    public javax.swing.JButton btnQuitar;
    public javax.swing.JComboBox cboTorneo;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JPanel pnlCompetidores;
    public javax.swing.JToolBar tbarExpandAndCollapse;
    public org.jdesktop.swingx.JXTaskPane tskpnlTorneo;
    public javax.swing.JTextField txtBuscar;
    public org.jdesktop.swingx.JXTreeTable xtreetblCompetidores;
    public org.jdesktop.swingx.JXTaskPaneContainer xtskpnlContainer;
    // End of variables declaration//GEN-END:variables

}
