/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package com.tdk.client.torneos;

import com.tdk.domain.security.Acceso;
import com.tdk.domain.torneo.Torneo;
import com.thorplatform.swing.SwingControllerFactory;
import com.thorplatform.swing.actions.NotifierSwingActionListener;
import com.thorplatform.swing.actions.SwingActionListener;
import com.thorplatform.swing.actions.ValidatePermision;
import java.awt.BorderLayout;
import java.io.Serializable;
import java.util.logging.Logger;
import org.openide.util.Lookup;
import org.openide.util.NbBundle;
import org.openide.windows.TopComponent;
import org.openide.windows.WindowManager;
import org.openide.util.Utilities;

/**
 * Top component which displays something.
 */
final class RegistrarCompatidoresTorneoTopComponent extends TopComponent {

    private static RegistrarCompatidoresTorneoTopComponent instance;
    /** path to the icon used by the component and its open action */
    static final String ICON_PATH = "com/tdk/client/torneos/competidor/competidor-16x16.png";

    private static final String PREFERRED_ID = "RegistrarCompatidoresTorneoTopComponent";
    
    private RegistrarCompetidorTorneoController registrarCompetidorController = null;

    private RegistrarCompatidoresTorneoTopComponent() {
        initComponents();
        afeterInitComponents();
        setName(NbBundle.getMessage(RegistrarCompatidoresTorneoTopComponent.class, "CTL_RegistrarCompatidoresTorneoTopComponent"));
        setToolTipText(NbBundle.getMessage(RegistrarCompatidoresTorneoTopComponent.class, "HINT_RegistrarCompatidoresTorneoTopComponent"));
        setIcon(Utilities.loadImage(ICON_PATH, true));
    }

    private void afeterInitComponents() {
        SwingControllerFactory scf = Lookup.getDefault().lookup(SwingControllerFactory.class);
        registrarCompetidorController = scf.createController(RegistrarCompetidorTorneoController.class);
        add(registrarCompetidorController.getForm(), BorderLayout.CENTER);
        
    }
    
    public void setTorneo(Torneo torneo) {
        if (registrarCompetidorController != null)
            registrarCompetidorController.setTorneo(torneo);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    /**
     * Gets default instance. Do not use directly: reserved for *.settings files only,
     * i.e. deserialization routines; otherwise you could get a non-deserialized instance.
     * To obtain the singleton instance, use {@link findInstance}.
     */
    public static synchronized RegistrarCompatidoresTorneoTopComponent getDefault() {
        if (instance == null) {
            instance = new RegistrarCompatidoresTorneoTopComponent();
        }
        return instance;
    }

    /**
     * Obtain the RegistrarCompatidoresTorneoTopComponent instance. Never call {@link #getDefault} directly!
     */
    public static synchronized RegistrarCompatidoresTorneoTopComponent findInstance() {
        TopComponent win = WindowManager.getDefault().findTopComponent(PREFERRED_ID);
        if (win == null) {
            Logger.getLogger(RegistrarCompatidoresTorneoTopComponent.class.getName()).warning(
                    "Cannot find " + PREFERRED_ID + " component. It will not be located properly in the window system.");
            return getDefault();
        }
        if (win instanceof RegistrarCompatidoresTorneoTopComponent) {
            return (RegistrarCompatidoresTorneoTopComponent) win;
        }
        Logger.getLogger(RegistrarCompatidoresTorneoTopComponent.class.getName()).warning(
                "There seem to be multiple components with the '" + PREFERRED_ID +
                "' ID. That is a potential source of errors and unexpected behavior.");
        return getDefault();
    }

    @Override
    public int getPersistenceType() {
        return TopComponent.PERSISTENCE_ALWAYS;
    }

    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    /** replaces this in object stream */
    @Override
    public Object writeReplace() {
        return new ResolvableHelper();
    }

    @Override
    protected String preferredID() {
        return PREFERRED_ID;
    }

    final static class ResolvableHelper implements Serializable {

        private static final long serialVersionUID = 1L;

        public Object readResolve() {
            return RegistrarCompatidoresTorneoTopComponent.getDefault();
        }
    }
}
